server:
  port: 8080
  shutdown: graceful
spring:
  datasource:
    url: jdbc:h2:file:<LOCAL_PATH>;DB_CLOSE_ON_EXIT=FALSE
    username: transferz
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  h2:
    console:
      enabled: true
      path: /h2-console
management:
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics'
config:
  maxPassengerCount: 150
